services:
  daskscheduler:
    image: ghcr.io/dask/dask:latest
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
  daskworker:
    image: ghcr.io/dask/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    deploy:
      replicas: 2
  # dasknb:
  #   image: ghcr.io/dask/dask-notebook:latest
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
  dagster-dagit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dagit
    ports:
      - 3000:3000
    volumes:
      - ./data/:/dags/data
      #- ./dags/:/dags
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
  dagster-daemon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "dagster-daemon run"
  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
  minio:
      image: minio/minio
      container_name: minio
      ports:
          - "9001:9001"
      environment:
          - MINIO_ROOT_USER=minioadmin
          - MINIO_ROOT_PASSWORD=minioadmin
      command: minio server minio_data --console-address ":9001"
volumes:
  dagster-postgres:
    driver: local
